name: pdd
description: "Pre-Departure Detention (PDD) data collection app."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0-333.2.beta

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.3.5
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  hive_flutter: ^1.1.0
  uuid: ^4.5.2
  hive: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  riverpod_generator: ^2.6.3
  freezed: ^2.5.7
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true
